name: mapbox_gl_dart
version: 0.2.2
description: Mapbox-gl wrapper for Dart. Library to use Mapbox GL JS in your web Dart projects.
homepage: https://github.com/andrea689/mapbox-gl-dart/
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  js: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.9
